### ISSUE TITLE
 library not found for -ldart (macos)

### ISSUE THREAD

**Issue by gcxfd** [DoumanAsh/dart-sys#2]
如图

![image](https://user-images.githubusercontent.com/69608605/135439507-28f52dc4-936b-456b-98d6-02f553987d15.png)

 build.rs 如下
```
use std::path::Path;

fn main() {
  let dart_path = Path::new("/usr/local/opt/dart/libexec");
  println!(
    r#"cargo:rustc-link-search=native={}"#,
    dart_path.join("bin").to_str().unwrap()
  );
  println!(r"cargo:rustc-link-lib=dart");
}
```

**Comment by DoumanAsh** [comment]
I'm sorry I do not speak chinese.

I'm not familiar with IOS or Mac developement, but if you plan to use dart FFI then follow these instructions
https://github.com/DoumanAsh/dart-sys#general-requirements

It explains that you should make dynamic library and load it using dart's FFI: `DynamicLibrary`
